<?php include(APP_PATH . 'admin/views/header.phtml'); ?>
<main class="form-signup text-center" style="padding-left:35%;padding-right:35%;">
 
 <?php echo $this->tag->form(""); ?>
 <h1 class="h3 mb-3 fw-normal">Update Product</h1>

  <div class="form-floating">
      <?php echo $this->tag->textField(["name","value" => $data['name'],"class"=>"form-control"]); ?>
      <label for="name">Product Name</label>
     </div>

  <div class="form-floating">
  <?php echo $this->tag->textArea(
    [
        "description",
        "cols" => 50,
        "rows" => 10,
        "value" => $data['description'],
        "class" => "form-control",

    ]
    );
    ?> 
       <label for="description">Description</label>
   </div>

  <div class="form-floating">
       <?php echo $this->tag->textField(["category" , "value" => $data["category"],"class"=>"form-control"]); ?>
       <label for="tags">Category</label>
   </div>

  <div class="form-floating">
       <?php echo $this->tag->textField(["price", "value" => $data["price"],"class"=>"form-control"]); ?>
       <label for="price">Price</label>
   </div>

   <div class="form-floating">
       <?php echo $this->tag->textField(["stock", "value" => $data["stock"],"class"=>"form-control"]); ?>
       <label for="stock">Stock</label>
   </div>

  <div class="form-floating">
       <?php echo $this->tag->submitButton(
   ["name" => "update","value"=> "Update Product",  "class" => "w-100 btn btn-lg btn-primary"]
); ?>
   </div>

   <div class="form-floating text-success">
       <?php if(isset($message))
       {
          echo $message;

       } ?>
   </div>
</form>