
<main class="p-5">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
    </div>

    <?php if (!isset($data)) {
    ?> <h3 class="text-center text-danger">Nothing to show</h3><?php
                                            } else {
                                                ?>
        <h2>All Products</h2>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Price</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Description</th>
                        <th scope="col">Quick View</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    foreach ($data as $k => $v) {
                    ?>
                        <tr>
                            <?php $desc = substr($v->description,0,50);
                            ?> 
                            <td> <?php echo $v->name  ?></td>
                            <td> <?php echo $v->category  ?></td>
                            <td> <?php echo $v->price  ?></td>
                            <td> <?php echo $v->stock  ?></td>
                            <td> <?php echo $desc."... " ?></td>

                            <!-- Edit and delete options -->
                            <td> <a class="btn btn-success" href="http://localhost:8080/products/quickView?id=<?php echo $v['_id']?>">View</a></td>
                        </tr> <?php
                                                }
                                ?>
                </tbody>
            </table>
        </div>
    <?php } ?>
    </form>


</main>