<header>
            <div class="collapse bg-dark" id="navbarHeader">
              <div class="container">
                <div class="row">
                  <div class="col-sm-8 col-md-7 py-4">
                  </div>
                  <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Contact</h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="navbar navbar-dark bg-dark shadow-sm">
              <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" 
                  stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                   stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24">
                   <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2
                    2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
                  <strong>Product</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarHeader" aria-controls="navbarHeader" 
                aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              </div>
            </div>
          </header>
        <!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                <?php 
                        ?>
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" height="400vh" width="90%",
                    src="<?php echo $data["img"]?>" alt="..." /></div>
                    <div class="col-md-6">
                        
                    
                        <h1 class="display-5 fw-bolder"><?php echo $data["name"]; ?></h1>
                        <p class="lead"><?php echo $data["description"]?></p>
                        <h3>Price:<?php echo $data["price"]?></h3>
                    </div>

                </div>
            </div>
        </section>
        <!-- Related items section-->

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">&copy; CEDCOSS Technologies</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>